version: '3'

services:

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  api:
    build:
      context: .
    ports:
      - '3000:3000'
    links:
      - db
    environment:
      - MONGO_HOST=db
    depends_on:
      - db
