version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secretPasswordToBeSetInAnotherPlaceInTheFuture
      - MYSQL_USER=desafio
      - MYSQL_PASSWORD=mudar123
      - MYSQL_DATABASE=b2wadds

  api:
    image: node:8-slim
    ports:
      - '3000:3000'
    links:
      - db
    environment:
      - DB_HOST=db
